---
# tasks file for ansible-role-smartgit

# -------------
# Platform conditional install and configuration
# -------------
- include: setup-Darwin.yml
  when:  ansible_os_family == 'Darwin'
  
- include: setup-Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
  