---
# Debian tasks file for ansible-role-smartgit

# -------------
# Install and configure Dependencies
# -------------
- name: Debian | ensure Java 7 present
  sudo: Yes
  apt: >
    name=openjdk-7-jre
    state=present
    update_cache=yes
    cache_valid_time=86400

# -------------
# Install and configure SmartGit
# -------------
- name: Debian | ensure SmartGit PPA repo present
  sudo: Yes
  apt_repository: repo='{{ smartgit_debian_ppa_repo }}'

- name: Debian | ensure SmartGit present
  sudo: Yes
  apt: >
    name=smartgit
    state=present
    update_cache=Yes
    cache_valid_time=86400    
